spring.application.name=boardG

spring.datasource.hikari.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hikari.jdbc-url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.hikari.username=scott
spring.datasource.hikari.password=1111
spring.datasource.hikari.connection-test-query=SELECT * from emp